version: 0.2

env:
  variables:
    APP_NAME: hello-world

phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws --version
      - AWS_DOCKER_REGISTRY=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - aws ecr get-login-password | docker login --username AWS --password-stdin $AWS_DOCKER_REGISTRY
      - REPOSITORY_URI=$AWS_DOCKER_REGISTRY/$APP_NAME
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Tagging and pushing the Docker images...
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":"%s","imageUri":"%s"}]' $APP_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json
